In [170]:
import pandas as pd
import numpy as np
from warnings import filterwarnings
filterwarnings('ignore')

In [171]:
raw_movies_df = pd.read_csv('Movies_DataSet.csv')

In [172]:
raw_movies_df.head().T

,0,1,2,3,4
index,0,1,2,3,4
budget,237000000,300000000,245000000,250000000,260000000
genres,Action Adventure Fantasy Science Fiction,Adventure Fantasy Action,Action Adventure Crime,Action Crime Drama Thriller,Action Adventure Science Fiction
homepage,http://www.avatarmovie.com/,http://disney.go.com/disneypictures/pirates/,http://www.sonypictures.com/movies/spectre/,http://www.thedarkknightrises.com/,http://movies.disney.com/john-carter
id,19995,285,206647,49026,49529
keywords,culture clash future space war space colony so...,ocean drug abuse exotic island east india trad...,spy based on novel secret agent sequel mi6,dc comics crime fighter terrorist secret ident...,based on novel mars medallion space travel pri...
original_language,en,en,en,en,en
original_title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter
overview,"In the 22nd century, a paraplegic Marine is di...","Captain Barbossa, long believed to be dead, ha...",A cryptic message from Bond’s past sends him o...,Following the death of District Attorney Harve...,"John Carter is a war-weary, former military ca..."
popularity,150.437577,139.082615,107.376788,112.31295,43.926995
production_companies,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]"
production_countries,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_3166_1"": ""US"", ""name"": ""United States o..."
release_date,2009-12-10,2007-05-19,2015-10-26,2012-07-16,2012-03-07
revenue,2787965087,961000000,880674609,1084939099,284139100
runtime,162.0,169.0,148.0,165.0,132.0
spoken_languages,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","[{""iso_639_1"": ""en"", ""name"": ""English""}]"
status,Released,Released,Released,Released,Released
tagline,Enter the World of Pandora.,"At the end of the world, the adventure begins.",A Plan No One Escapes,The Legend Ends,"Lost in our world, found in another."
title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter
vote_average,7.2,6.9,6.3,7.6,6.1
vote_count,11800,4500,4466,9106,2124
cast,Sam Worthington Zoe Saldana Sigourney Weaver S...,Johnny Depp Orlando Bloom Keira Knightley Stel...,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Christian Bale Michael Caine Gary Oldman Anne ...,Taylor Kitsch Lynn Collins Samantha Morton Wil...
crew,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...","[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...","[{'name': 'Thomas Newman', 'gender': 2, 'depar...","[{'name': 'Hans Zimmer', 'gender': 2, 'departm...","[{'name': 'Andrew Stanton', 'gender': 2, 'depa..."
director,James Cameron,Gore Verbinski,Sam Mendes,Christopher Nolan,Andrew Stanton

In [173]:
raw_movies_df.shape

(4803, 24)

In [174]:
raw_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [175]:
raw_movies_df.duplicated().sum()

np.int64(0)

In [176]:
raw_movies_df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [177]:
movies_df = raw_movies_df[['title','genres','keywords','overview','tagline','release_date','original_language','vote_average','vote_count','cast','director']].copy()

In [178]:
movies_df.head()

,title,genres,keywords,overview,tagline,release_date,original_language,vote_average,vote_count,cast,director
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,2009-12-10,en,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",2007-05-19,en,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski
2,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,2015-10-26,en,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes
3,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Following the death of District Attorney Harve...,The Legend Ends,2012-07-16,en,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan
4,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",2012-03-07,en,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton

In [179]:
movies_df.shape

(4803, 11)

In [180]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              4803 non-null   object
 1   genres             4775 non-null   object
 2   keywords           4391 non-null   object
 3   overview           4800 non-null   object
 4   tagline            3959 non-null   object
 5   release_date       4802 non-null   object
 6   original_language  4803 non-null   object
 7   vote_average       4803 non-null   float64
 8   vote_count         4803 non-null   int64
 9   cast               4760 non-null   object
 10  director           4773 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 412.9+ KB

In [181]:
movies_df.isnull().sum()

title                  0
genres                28
keywords             412
overview               3
tagline              844
release_date           1
original_language      0
vote_average           0
vote_count             0
cast                  43
director              30
dtype: int64

In [182]:
movies_df['year'] = (
    pd.to_datetime(movies_df['release_date'], errors='coerce')
    .dt.year
    .astype('Int64')  # keeps NaN
    .astype(str)
    .replace('<NA>', '')
)

In [183]:
movies_df.drop('release_date', axis=1, inplace=True)

In [184]:
cols = [
    'title','genres','keywords','overview','tagline','cast','director'
]

movies_df[cols] = movies_df[cols].fillna('')

In [185]:
movies_df.isnull().sum()

title                0
genres               0
keywords             0
overview             0
tagline              0
original_language    0
vote_average         0
vote_count           0
cast                 0
director             0
year                 0
dtype: int64

In [186]:
movies_df.columns

Index(['title', 'genres', 'keywords', 'overview', 'tagline',
       'original_language', 'vote_average', 'vote_count', 'cast', 'director',
       'year'],
      dtype='object')

In [187]:
def create_tags(x):
    x = x.copy()

    x['tags'] = (
        (x['title'] + " ") * 3 +
        x['overview'] + " " +
        (x['genres'] + " ") * 3 +
        (x['keywords'] + " ") * 2 +
        (x['cast'] + " ") * 2 +
        (x['director'] + " ") * 3 +
        x['tagline'] + " " +
        x['original_language'] + " " +
        x['year']
    )


    x['tags'] = (
        x['tags']
        .str.lower()
        .str.replace(r'\s+', ' ')
        .str.strip()
    )

    return x

In [188]:
movies_df = create_tags(movies_df)

In [189]:
movies_df.head(2)

,title,genres,keywords,overview,tagline,original_language,vote_average,vote_count,cast,director,year,tags
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,en,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,2009,"avatar avatar avatar in the 22nd century, a pa..."
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",en,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,2007,pirates of the caribbean: at world's end pirat...

In [190]:
movies_df['tags'][0]

'avatar avatar avatar in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction action adventure fantasy science fiction action adventure fantasy science fiction culture clash future space war space colony society culture clash future space war space colony society sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez james cameron james cameron james cameron enter the world of pandora. en 2009'

In [191]:
import re
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [192]:
lemmatizer = WordNetLemmatizer()

In [193]:
def preprocess_tags(text):

  # removing punctuation
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

  # lemmatizer each word
  text = ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

  return text

In [194]:
movies_df['tags'] = movies_df['tags'].apply(preprocess_tags)

In [195]:
movies_df['tags'][0]

'avatar avatar avatar in the 22nd century a paraplegic marine is dispatched to the moon pandora on a unique mission but becomes torn between following order and protecting an alien civilization action adventure fantasy science fiction action adventure fantasy science fiction action adventure fantasy science fiction culture clash future space war space colony society culture clash future space war space colony society sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez sam worthington zoe saldana sigourney weaver stephen lang michelle rodriguez james cameron james cameron james cameron enter the world of pandora en 2009'

**Why TF-Iraw_movies_df over CountVectorizer:**

```
CountVectorizer → just counts word frequency
                  "action" appears 500x → gets too dominant

TF-Iraw_movies_df          → balances frequency vs uniqueness
                  common words like "action" get lower weight
                  unique words get higher weight → better similarity

In [196]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [197]:
# Initialize TF-Iraw_movies_df Vectorizer to convert text tags into numerical vectors
# We use unigrams and bigrams to capture phrases like "Science Fiction"

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2,
)

In [198]:
movies_df.reset_index(drop=True,inplace=True)

In [199]:
tfidf_matrix = tfidf.fit_transform(movies_df['tags'])

In [200]:
print(tfidf_matrix.shape)

(4803, 10000)

In [201]:
indices = pd.Series(
    movies_df.index,
    index=movies_df['title'].str.lower().str.strip()
).drop_duplicates()

## IMDB Formula:

**WR = (v/(v+m)) × R + (m/(v+m)) × C**
*  v = movie's vote count
*  m = minimum votes required (threshold)
*  R = movie's vote average
*  C = mean vote average across all movies

In [202]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [203]:
# Constants calculated from the entire dataset
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.60)

In [204]:
def weighted_rating(x, C=C, m=m):
  v = x['vote_count']
  R = x['vote_average']
  return (v / (v + m)) * R + (m / (m + v)) * C

**Full flow summary:**
```
Input movie
    → find its vector
    → compare vs all 4800 movies (cosine similarity)
    → take top 100 similar
    → filter + deduplicate
    → score each by similarity + IMDB quality
    → normalize both scores to same scale
    → blend 60/40
    → return top 5

In [205]:
def recommend(movie, top_n=5, pool_size=100):
    """
    Hybrid Recommendation System
    ----------------------------
    1. Finds content similarity using TF-Iraw_movies_df and Cosine Similarity.
    2. Filters a candidate pool of 100 movies.
    3. Calculates Weighted Ratings to prioritize quality movies.
    4. Blends scores (60% Similarity / 40% Rating) for the final result.
    """

    # Standardize input and find movie index
    movie_lower = movie.lower().strip()
    if movie_lower not in indices:
        return "Movie not found in database."

    idx = indices[movie_lower]

    # Step 1: Compute Cosine Similarity for the target movie
    sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix)[0]

    # Step 2: Create a candidate pool (Top 100 similar movies)
    # We take 100 to ensure we have enough "good" movies to rank by rating
    sim_indices = sim_scores.argsort()[::-1][1:pool_size + 1]
    rec = movies_df.iloc[sim_indices].copy()
    rec['sim_score'] = sim_scores[sim_indices]

    # Step 3: Data Cleaning
    rec = rec[rec['title'].str.lower() != movie_lower]
    rec = rec.drop_duplicates(subset='title')

    # Step 4: Apply Weighted Rating
    rec['weighted_rating'] = rec.apply(weighted_rating, axis=1)

    # Step 5: Normalization
    # We scale both scores to [0, 1] so they can be added fairly
    scaler = MinMaxScaler()
    rec[['norm_sim', 'norm_rating']] = scaler.fit_transform(
        rec[['sim_score', 'weighted_rating']]
    )

    # Step 6: The Hybrid Blend
    # 0.6 and 0.4 are the weights for Content vs. Quality
    rec['hybrid_score'] = (0.6 * rec['norm_sim']) + (0.4 * rec['norm_rating'])

    # Step 7: Final Sort
    cols_to_show = ['title', 'year', 'genres', 'sim_score', 'hybrid_score']
    return rec.sort_values(by='hybrid_score', ascending=False)[cols_to_show].head(top_n)

In [206]:
recommend('the terminator')

,title,year,genres,sim_score,hybrid_score
279,Terminator 2: Judgment Day,1991,Action Thriller Science Fiction,0.613183,0.932165
2403,Aliens,1986,Horror Action Thriller Science Fiction,0.417662,0.699024
93,Terminator 3: Rise of the Machines,2003,Action Thriller Science Fiction,0.452574,0.511880
108,Terminator Genisys,2015,Science Fiction Action Thriller Adventure,0.450894,0.495548
95,Interstellar,2014,Adventure Drama Science Fiction,0.177813,0.490041

In [207]:
import pickle


pickle.dump(movies_df, open('movie_list.pkl', 'wb'))


pickle.dump(tfidf_matrix, open('similarity_vectors.pkl', 'wb'))


pickle.dump(tfidf, open('tfidf_model.pkl', 'wb'))


pickle.dump(indices, open('indices_map.pkl', 'wb'))

print("All files pickled successfully!")

All files pickled successfully!